### PR TITLE
Prep release

### PR DESCRIPTION
**Pull request by ackerlar**

### CODE REVIEW

**Comment by dbarbi** [comment]
Hi Lars. I found the update_chunk_date_file too. Does that solve your issue?

**Comment by ackerlar** [comment]
@dbarbi Yes, it solved the issue for me.

**Comment by dbarbi** [comment]
Great, will merge that now.

**Comment by dbarbi** [comment]
Actually I won't, as it is still in draft mode

**Comment by ackerlar** [comment]
I have done another update. The

**Pull request closed without merging**
