### PR TITLE
Feature/transient forcing

### PR DESCRIPTION
**Pull request by mandresm**
Fixes for #198

### CODE REVIEW

**Comment by mandresm** [comment]
@xshi-awi , this fix will be merged soon and should fix the problem you are experiencing.

**Comment by pgierz** [comment]
Aha....ok, so this is what happens when any you just catch "any random exception". Oops

**Review by pgierz — APPROVED** [review]

**Comment by pgierz** [comment]
Merging now, is there a tag as well?

**Comment by mandresm** [comment]
> Merging now, is there a tag as well?

Yes, and it is also in the monorepo

**Comment by pgierz** [comment]
I'll take care of that one now

**Comment by mandresm** [comment]
@xshi-awi , you can go ahead now, `esm_versions upgrade` and try it out.

**Comment by xshi-awi** [comment]
Thanks, that works.

**Comment by xshi-awi** [comment]
in namelists.py, all the "cobl" should be replaced by "cobld", could you please update that? Thanks so much in advance.

**Comment by pgierz** [comment]
yes, thanks @xshi-awi. My brain is seemingly faster than my fingers. I'll make a new PR with the correction.

**Pull request merged**
